### ISSUE TITLE
自测用例以及BUG模板(此条为用例名称或者BUG名称)

### ISSUE THREAD

**Issue by youngiyang1990** [getHighTech/wanchehuiPlatform#1]
前置条件:
1.前置条件1
2.前置条件2

操作步骤:
1.操作步骤1
2.操作步骤2

预期结果:
1.预期结果1
2.预期结果2

补充说明:
对该BUG或者该用例的补充说明

(然后在右侧选择功能模块->Milestone,bug等级->Labels)

**Comment by simontaosim** [comment]
完成请测试验收
