### ISSUE TITLE
商家后台会员管理页面给用户禁卡后依然在页面显示

### ISSUE THREAD

**Issue by duanlintai** [getHighTech/wanchehuiPlatform#22]
- [前置条件] 
1.已登录商家后台
2.进入会员管理页面
- [操作步骤] 
1.点击用户‘禁卡’按钮
2.点击‘Yes’按钮
- [预期结果]
 系统提示“解除绑定成功”，页面不再显示用户信息
- [实际结果]
页面依然显示用户信息，需重新刷新后用户信息才会不显示

**Comment by youngiyang1990** [comment]
新版本已经解决，请验收测试

**Comment by duanlintai** [comment]
已修复，测试通过
