### ISSUE TITLE
商家后台在加载数据量稍大的订单管理页面后，会员管理和卡片管理页面加载缓慢

### ISSUE THREAD

**Issue by duanlintai** [getHighTech/wanchehuiPlatform#23]
- [前置条件] 
用户已登录商家后台
- [操作步骤]
1.点击订单管理 
2.点击会员管理
3.点击卡片管理
- [预期结果] 
显示会员用户信息，显示会员卡信息
- [实际结果]
订单管理页面的加载影响会员管理页面和卡片管理页面，加载缓慢，需要5-10秒左右才能加载出数据

**Comment by youngiyang1990** [comment]
新版本已经解决，请验收测试

**Comment by duanlintai** [comment]
已修复，测试通过
