### ISSUE TITLE
商家后台发布商品功能上传多图保存后，再次打开修改商品窗口上传多图区域出现异常

### ISSUE THREAD

**Issue by duanlintai** [getHighTech/wanchehuiPlatform#24]
- [前置条件] 
用户已登录商家后台
- [操作步骤] 
1.进入我的店铺页面
2.点击发布商品按钮
3.商品多图预览框点击‘点击选择图片’
4.上传图片
5.其他各项输入合法
6.点击‘确认’按钮
7.点击商品后‘修改’按钮查看多图输入框
- [预期结果]
正常显示 
- [实际结果]
出现异常显示，详见下图
![default](https://user-images.githubusercontent.com/40376906/42802459-a67c0e30-89d5-11e8-933b-995cfcff95b7.jpeg)

**Comment by youngiyang1990** [comment]
新版本已经解决，请验收测试

**Comment by duanlintai** [comment]
已修复，测试通过
