### ISSUE TITLE
商家后台发布商品功能窗口所有输入框下拉列表框显示异常

### ISSUE THREAD

**Issue by duanlintai** [getHighTech/wanchehuiPlatform#25]
- [前置条件] 
用户已登录进入商家平台
- [操作步骤] 
1.进入我的店铺页面
2.点击发布商品按钮
3.点击输入框，显示下拉列表框
4.点击浏览器右侧滚动条
- [预期结果] 
页面窗口正常上下滚动显示
- [实际结果]
输入框显示的下拉列表框上下滚动显示，详见下图
![default](https://user-images.githubusercontent.com/40376906/42803039-4a932750-89d7-11e8-84f5-8fb23fad48de.jpeg)

**Comment by youngiyang1990** [comment]
新版本已经解决，请验收测试

**Comment by duanlintai** [comment]
已修复，测试通过
