### ISSUE TITLE
商家后台高级会员管理页面查看详情下应为‘我的团队’

### ISSUE THREAD

**Issue by duanlintai** [getHighTech/wanchehuiPlatform#39]
- [前置条件] 
用户已登录进入高级会员管理页面
- [操作步骤] 
鼠标移至查看详情下操作按钮
- [预期结果] 
应为‘我的团队’
- [实际结果] 
查看详情下显示的‘授卡’

**Comment by youngiyang1990** [comment]
修改title,已经解决

**Comment by duanlintai** [comment]
已修复，测试通过
